### ISSUE TITLE
Brainstorming for songs dataset in MIDI format

### ISSUE THREAD

**Issue by sachinravi14** [AI-ON/Few-Shot-Music-Generation#2]
Details of the requirements for the dataset can be found in the proposal. We are looking for suggestions for creating this dataset, including:
* Possible sources for the raw data.
* How it can be collected.
* The format of the collected dataset.

**Comment by souravsingh** [comment]
@sachinravi14 For datasets, Here are some we can make use of -
[The Lakh MIDI dataset](http://colinraffel.com/projects/lmd/)
[Dataset from Reddit](https://www.reddit.com/r/datasets/comments/3akhxy/the_largest_midi_collection_on_the_internet/)
[Piano MIDI dataset](http://www.piano-midi.de/)
[Stanford MuseData](http://musedata.stanford.edu/)

**Comment by iansimon** [comment]
Another dataset to consider is [this one from Yamaha](http://www.yamahaden.com/midi-files).  It's what we used to train [this LSTM model](https://magenta.tensorflow.org/performance-rnn) that generates piano performances.

Advantages: has composer labels, performance-trained samples generally sound better than score-trained samples

**Comment by sagelywizard** [comment]
In _Hierarchical Variational Autoencoders for Music_, Roberts et al crawled 1.5M MIDI files from the Internet, but I can't find the dataset anywhere. I'm guessing that's due to copyright issues. It sounds nice to have a dataset that large, but if the goal is to have reproducible results, it might be good to use a dataset with a good license (maybe Lakh?).

**Comment by sachinravi14** [comment]
The Lakh MIDI dataset seems to have 45,129 entries linked the Million Songs dataset. Does anyone know, for these entries, how many unique artists these songs corresponds to and what is the average number of songs per artist?

**Comment by souravsingh** [comment]
@sachinravi14 There is a json file which matches the MD5 checksums of the files, the file also contains the artist names. Some of the artist names like Beatles, Beethoven are present.

**Comment by sachinravi14** [comment]
@souravsingh I see; If someone can get some exact numbers on those statistics, it would be nice as we can evaluate whether the Lakh dataset can be used for our purpose.

**Comment by sagelywizard** [comment]
I count 11483 artists in "LMD-matched metadata", but I'm confused about the 45129 number. I'm counting 116189 MIDI files in the LMD-matched dataset.

**Comment by siddharth-agrawal** [comment]
@sachinravi14 Got the statistics for you. Firstly, the number of entries from the Million Song Dataset in LMD-matched is only 31034. This is because multiple MIDI entries are possible per MSD entry. As @sagelywizard said, there are 11483 unique artists. (without any processing of the artist names) These numbers make the dataset unsuitable for the task.

**Comment by siddharth-agrawal** [comment]
@sachinravi14 I might have found a data source suitable for the task. I wrote a small script to get the artists and the number of songs for each artist from here: https://freemidi.org/artists. The output of my program is here: https://pastebin.com/GLWQnTw1. As can be seen from the output, there are quite a few artists with a double-digit number of songs. I can give you additional statistics if this looks interesting.
